image: docker:latest
services:
  - docker:dind

stages:
  - "Docker Build"
  - "Downstream Triggers"

BugAudit Platform Build:
  stage: "Docker Build"
  script:
    - sh docker-builder
  only:
    - master

BugAudit Environment Build:
  stage: "Downstream Triggers"
  trigger: bugaudit/bugaudit-cli
  only:
    - master
